---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: mmg-again
--- 
  kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: mmg-again
    namespace: mmg-again
  spec:
    replicas: 3
    strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
    selector:
      matchLabels:
        app: mmg-again
    template:
      metadata:
        labels:
          app: mmg-again
      spec:
        containers:
          - name: mmg-again
            image: localhost:5000/mmg_image2:v1
            imagePullPolicy: Always
            resources:
              limits:
                cpu: "0.25"
                memory: "512Mi"
              requests:
                cpu: "250m"
                memory: "50Mi"
---
  kind: Service
  apiVersion: v1
  metadata:
    name: mmg-again
    namespace: mmg-again
  spec:
    selector:
      app: mmg-again
    ports:
      - name: http
        port: 8101
        protocol: TCP
        targetPort: 8080
    type: LoadBalancer
      